name: Deploy to AWS S3 bucket

on:
  pull_request:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-18.04

    steps:
        - uses: actions/checkout@master

        - name: Deploy
            env:
                AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                run: |
                aws s3 cp \
                    --recursive \
                    --region ${{ secrets.AWS_REGION }} \
                    ${{ secrets.SOURCE_DIR }}  s3://${{ secrets.AWS_S3_BUCKET }}        