# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-18.04

    strategy:
      matrix:
        node-version: [12.16.1]

    steps:
      - uses: actions/checkout@v1

      - name: Print a greeting
        env:
          MY_VAR: Welcome to my C.I process
          FIRST_NAME: Tejas
          MIDDLE_NAME: Shailesh
          LAST_NAME: Sabunkar
        run: |
          echo $MY_VAR $FIRST_NAME $MIDDLE_NAME $LAST_NAME.

      - name: Node version ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Installing all the npm dependencies of specific versions using ci
        run: npm ci

      - name: Checking for Linting..
        run: npm run lint

      - name: Checking for build prod and AOT..
        run: npm run build

        env:
          CI: true
